version: '3.8'

services:
  database:
    image: postgres:15
    container_name: dodo_db
    restart: always
    environment:
      POSTGRES_DB: dodo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dodo_backend
#    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/dodo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8082:8081"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dodo_frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://80.64.24.107:8082/

volumes:
  pgdata:
