events {}

http {
    server {
        listen 80;

        server_name www.find-combo.ru find-combo.ru;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name www.find-combo.ru find-combo.ru;

        ssl_certificate /etc/letsencrypt/live/find-combo.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/find-combo.ru/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;


        location /portainer/ {
            proxy_pass http://localhost:9000/;
        }

#         location /api/static/ {
#             proxy_pass http://go_app:8080/;
#
#             add_header 'Access-Control-Allow-Origin' '*' always;
#             add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
#             add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
#             if ($request_method = OPTIONS) {
#                 return 204;
#             }
#
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#         }

        location /api/ {
            proxy_pass http://backend:8081/api/;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
